// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TotalSprReport.Data;

#nullable disable

namespace TotalSprReport.Migrations
{
    [DbContext(typeof(SprDBContext))]
    [Migration("20230913081221_Spr-Report")]
    partial class SprReport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TotalSprReport.Models.Detil_SPR", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdRef")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("StatusDisetujui")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TanggalRencanaDiterima")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdRef");

                    b.HasIndex("MaterialId");

                    b.ToTable("Detil_SPR");
                });

            modelBuilder.Entity("TotalSprReport.Models.Header_SPR", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LokasiPeminta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Peminta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProyekId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TanggalMinta")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProyekId");

                    b.ToTable("Header_SPR");
                });

            modelBuilder.Entity("TotalSprReport.Models.Materials", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TipeMaterial")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Material");
                });

            modelBuilder.Entity("TotalSprReport.Models.Proyek", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LokasiProyek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaProyek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Proyek");
                });

            modelBuilder.Entity("TotalSprReport.Models.Detil_SPR", b =>
                {
                    b.HasOne("TotalSprReport.Models.Header_SPR", "Header_SPR")
                        .WithMany()
                        .HasForeignKey("IdRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TotalSprReport.Models.Materials", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Header_SPR");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("TotalSprReport.Models.Header_SPR", b =>
                {
                    b.HasOne("TotalSprReport.Models.Proyek", "Proyek")
                        .WithMany()
                        .HasForeignKey("ProyekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyek");
                });
#pragma warning restore 612, 618
        }
    }
}
